---
title: "project"
output:
    html_document:
        code_folding: hide

---
asdasdasdasd
## We will use the next packages:
```{r setup, eval = FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)

```

``` {r datainitialization, eval = FALSE}
# data initialization:
data1 <- read.csv('project.csv')

myData = select(data1, -1:-3, -5:-23, -25, -31, -33, -36, -38:-39, -41:-42, -45, -47:-49)

levels(myData$Severity) <- c(1:4)

myData <- myData %>% 
  rename(
    temperature = Temperature.F.,
    humidity = Humidity...,
    pressure = Pressure.in.,
    visibility = Visibility.mi.,
    wind_direct = Wind_Direction,
    wind_speed = Wind_Speed.mph.,
  )
```


```{r cars}

head(myData)
```

## Including Plots
```{r temperature}
hist(myData$temperature)
```

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
